Home intro slider
jeanpco/st-george-church pull request #4
Opened 2020-09-07 01:36 UTC by Romano78

The home intro slider is completed. Just I did not know if we needed to implemented the arrows, so I made the slide autoplay. Also for the progress bar I thought it was better to start with 0 and then go up or down. In Figma the progress bar is already like almost full. Also the image is cropped on Figma but I did no crop it here. Let me know if you need me to change stuff.

2020-09-07 18:52 UTC, jeanpco requested changes
1. This should be centered. Also, it seems like the image is always rendering. Please make sure to test that fully.
<img width="1231" alt="Screen Shot 2020-09-07 at 2 45 04 PM" src="https://user-images.githubusercontent.com/21043627/92412267-47d77380-f119-11ea-9bb6-7d1437a3b341.png">
<img width="896" alt="Screen Shot 2020-09-07 at 2 45 14 PM" src="https://user-images.githubusercontent.com/21043627/92412290-5de53400-f119-11ea-8e6b-02f000f58723.png">

2. Image is very blurred out. Should be to a minimum what's in Figma.
<img width="908" alt="Screen Shot 2020-09-07 at 2 46 14 PM" src="https://user-images.githubusercontent.com/21043627/92412293-66d60580-f119-11ea-9ea1-92cf3b7a5f77.png">

3. Graphic on desktop is too small
<img width="132" alt="Screen Shot 2020-09-07 at 2 46 35 PM" src="https://user-images.githubusercontent.com/21043627/92412312-76554e80-f119-11ea-9c34-4396459df48a.png">

4. Space between body and link is too narrow.
<img width="305" alt="Screen Shot 2020-09-07 at 2 46 42 PM" src="https://user-images.githubusercontent.com/21043627/92412320-7ce3c600-f119-11ea-856f-29c71d018fd9.png">

5. Space between slider and progress is a little bit too narrow.
<img width="456" alt="Screen Shot 2020-09-07 at 2 46 57 PM" src="https://user-images.githubusercontent.com/21043627/92412335-89681e80-f119-11ea-8559-7d1d3e9b33b1.png">

6. On mobile, title line-height should be tighter
<img width="258" alt="Screen Shot 2020-09-07 at 2 47 37 PM" src="https://user-images.githubusercontent.com/21043627/92412355-9422b380-f119-11ea-961f-cb539e687c6d.png">

7. Too much spacing on mobile between title and body.
<img width="353" alt="Screen Shot 2020-09-07 at 2 47 47 PM" src="https://user-images.githubusercontent.com/21043627/92412388-b87e9000-f119-11ea-9c26-ab1c40e50ddb.png">

2020-09-07 19:11 UTC, jeanpco requested changes

2020-09-07 19:11 UTC, jeanpco commented on src/components/About/index.js
> +  `)
This query should come from index page directly and be filtered on the GraphQL query directly.

2020-09-07 19:11 UTC, jeanpco commented on src/components/About/index.js
> +        {aboutTitle}
missing safety check around title

2020-09-07 19:11 UTC, jeanpco commented on src/components/About/index.js
> +          {aboutText}
missing safety check around text

2020-09-07 19:11 UTC, jeanpco commented on src/components/About/style.js
> +    height: 152px;
Height should be dedicated by content. Do not set fixed height. Let's also avoid width declaration and only restrict width on the container. Unless you absolutely need it.

2020-09-07 19:11 UTC, jeanpco commented on src/components/About/style.js
> +    }
let's remove if unnecessary

2020-09-07 19:11 UTC, jeanpco commented on src/components/Drawer/index.js
> +          </Title>
missing safety check

2020-09-07 19:11 UTC, jeanpco commented on src/components/Drawer/index.js
> +                              <span>
Why the span around the icon?

2020-09-07 19:11 UTC, jeanpco commented on src/components/Drawer/styles.js
> +    span {
I see that you use span for styling here.

I'd suggest you create another emotion container like `IconContainer` and style that instead. Will be cleaner and will avoid potential conflicts

2020-09-07 19:11 UTC, jeanpco commented on src/components/Footer/index.js
> +  //   : ''
if unnecessary, let's remove

2020-09-07 19:11 UTC, jeanpco commented on src/components/Footer/index.js
>    const footerGraphic = data?.footer?.nodes[0]?.metadata.footer_graphic?.local
Missing optional chaining operator on metadata => metadata?.footer_graphic?.local

2020-09-07 19:11 UTC, jeanpco commented on src/components/Footer/styles.js
> +      padding: 42px 42px;
change padding: 42px 42px to 42px

2020-09-07 19:11 UTC, jeanpco commented on src/components/Slider/index.js
> +  const normalise = (value) => ((value - 0) * 100) / (imgLength - 1)
Very nice!

2020-09-07 19:11 UTC, jeanpco commented on src/components/Slider/index.js
> +  customClassName: PropTypes.any,
customClassName is probably a string. Also, I'd like simply "className"

2020-09-07 19:11 UTC, jeanpco commented on src/components/Slider/styles.js
> +`
Have you tried calling theme with props? instead of calling the file

2020-09-07 19:11 UTC, jeanpco commented on src/components/SliderSection/SliderSectionMobile.js
> +export default SliderSectionMobile
Why are you using 2 different container? It seems to me that this can be achieve with only 1 component that deals with desktop and mobile at once

2020-09-07 20:59 UTC, Romano78 commented on src/components/Drawer/index.js
> +                              <span>
to have some spacing between text and icon ? is it not the best practice ?

2020-09-07 21:05 UTC, Romano78 commented on src/components/Slider/index.js
> +  const normalise = (value) => ((value - 0) * 100) / (imgLength - 1)
Thank you !

2020-09-11 12:33 UTC, jeanpco requested changes
1. Spacing between menu element is too narrow.
<img width="344" alt="Screen Shot 2020-09-11 at 8 24 58 AM" src="https://user-images.githubusercontent.com/21043627/92925711-e65d2080-f408-11ea-9db1-6b16c00a3192.png">

2. Design and built sentence is in wrong font
<img width="195" alt="Screen Shot 2020-09-11 at 8 25 09 AM" src="https://user-images.githubusercontent.com/21043627/92925695-e0673f80-f408-11ea-98ee-e76aa4dfd72e.png">

3. The height should be 100% and the text logo and social media should always remain at the bottom of the page. To achieve this, make the container 100%, add a div around menu title and menu element and another div around about us title and body text + text logo + social media and make 100% height container 

display: flex;
flex-direction: column:
justify-content: space-between;

<img width="411" alt="Screen Shot 2020-09-11 at 8 25 51 AM" src="https://user-images.githubusercontent.com/21043627/92925732-eeb55b80-f408-11ea-8baa-962279a8f76f.png">

4. Menu title should not be an h1. Only 1 h1 per page.
<img width="534" alt="Screen Shot 2020-09-11 at 8 26 05 AM" src="https://user-images.githubusercontent.com/21043627/92925909-3f2cb900-f409-11ea-852b-9e599285a892.png">

5. Overlay when menu is open should not be transparent black but blurred. please refer to figma
<img width="812" alt="Screen Shot 2020-09-11 at 8 26 46 AM" src="https://user-images.githubusercontent.com/21043627/92925915-4358d680-f409-11ea-89dd-4bd52e1e88d3.png">

6. Text body font is wrong
<img width="312" alt="Screen Shot 2020-09-11 at 8 27 05 AM" src="https://user-images.githubusercontent.com/21043627/92926013-64b9c280-f409-11ea-821b-9e4f4d3b5fe8.png">

2020-09-14 21:39 UTC, merged